language: java
install: mvn package
addons:
  sonarcloud:
    organization: sonarkeyauth
    token:
      secure: "ZLTTAGGQL6hc3xM9NU45rU3RDYuj8iN6O12+ClLhUd2ltvncfLhYKC/VSarxskqhRbT6MeI3G3kTyGLpkuvuUvWVDHVSRu68Utc0lEEtz8sAdd3zD1OY0BK3M0n8hDuQtms3ZJvjKlncmSy8wBWAB2+AQwZWihOqRup/00Yp6nkk9TGMh0N0V42tkA31SGTXXeuM7QNkR4w8CYTeyR8ktANzn57uD2UznWSyvRbqSARD8EYskAbaEULz+YW3H2vY7PEY3ncHUwShnAmjXeg+PxFsiF8dZ5h1bs+bwvr4yrBitQmeq/24eee36UZLTE0caxKEdKLP7O1yphXUJv7id6OZIy0538cdaMuwz549oTg9q8U7KVi5Z3CImM+Qz5IoSwzBbSSggja8/wulaD8T0S1lzRFVRBuREVIJ5g7jYoXNW71txwLqkUhaYSiFq7roa3w3hPxpOnrjCDzR2DatAL7+gwFrUgYJ1Txj6jAVLLsRny9Ft3yWUDhRjYuFK4sPoPql6MyHglISQo78zZmBvWGFCdCl8YnVdtfS0308NkpvhEwwayflKWUTDwPEOshKblwV/ka+fj+3IbWqmfTKmifsvm7u5GTlg5+nmki0qH4dRu76ueK0/DizesHF5g8TMZGxzNi0yMcApX7b1rkXxifywu6dH3unEddwdWJLWHU="

script:
- sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: "ZA+dTwtoySReXbdvCJ49R2SN/30pXWAKcB2Fr1z6drjk0tx0LuWHJT1Ikh77AI64LKsqTBoVH5AccsKxrR5zXsAJhY+dn/w0F/5XW1PjS/e60VoR+Unzs+v1PaIGhulGR9xNcpL2NmpvcsB1Xn7AvrfsewoMrs01jQOn/tViXzSBYyQoTUh6+X+BbC68KIYakAvaehBo9c4ticrpP125hJgNprE8P4bBaCEK2UV5Cp7ghmwdBUXtEW4w9bG1RNXxoTwOf0M0SUXzqqCUS4TUmjPLu/+WBJuPnrbA14nNBNIFYjVdAazaYKStLFXAt10/N6Rb1C1br1Ydr8imjpgd5Xhb+46vkmjzi7z6l6XwsfD5Pic3XmL5fuV0d2/O/AZOtQpnw22BfRnCOrfDhYir2JzT3hohNPYCJ9y3kW082m/TaOR3wRPbqkQtVFRnVmA+tiSq+ixY/TmpXBGuj6Va/DaFSU1AgTPtX5ybuQg2JzT5Dnu4TGNCl7CAjUri1oHuyMYivNY5IzcdApzeDaZEf1JEK8Le28eZV1oe+ODFr/971LKWCzY2TD52G69EBMVkVimV/d1aUBZO5RrtQtuLDKkFUJYjxCvhSyfAcfuIt1NrInUnk3fIlAm7iq7dqjpkx9UD6Ti2IYA8szifiwasZM+AgjoztBNmYY6c8nZfVaM="
  app:
    master: aditihelloapp
    test: aditihellotestapp
