language: java
install: mvn package
addons:
  sonarcloud:
    organization: sonarkeyauth
    token: 1897fd76de101613ada8a2eec90ae770924d7321
script:
- sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: HEROKU_API_KEY
  app:
    master: aditihelloapp
    test: aditihellotestapp
