language: java
install: mvn package
addons:
  sonarcloud:
    organization: sonarkeyauth
    token: $SONAR_TOKEN
script:
- sonar-scanner
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app:
    master: aditihelloapp
