language: java
install: mvn package
addons:
  sonarcloud:
    organization: "sonarkeyauth"
    token: "1897fd76de101613ada8a2eec90ae770924d7321"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
deploy:
  provider: heroku
  api_key: "79805b4b-a06b-4af5-8a94-06b4c65870ba"
  app:
    master: aditihelloapp
    test: aditihellotestapp
